pipeline {
    agent any

    tools {
        python 'Python3'
    }

    environment {
        GIT_REPO = 'https://github.com/BBBenson/alx-backend-python.git'
    }

    

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: "${env.GIT_REPO}",
                    credentialsId: 'github-creds'
            }
        }

        stage('Install dependencies') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app/tests/ --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
